INSERT INTO ingredient (name, type) VALUES ('Flour Tortilla', 'WRAP'), 
										   ('Corn Tortilla', 'WRAP'),
										   ('Ground Beef', 'PROTEIN'),
										   ('Carnitas', 'PROTEIN'),
										   ('Diced Tomatoes', 'VEGGIES'),
										   ('Lattuce', 'VEGGIES'),
										   ('Cheddar', 'CHEESE'),
										   ('Monterrey Jack', 'CHEESE'),
										   ('Salsa', 'SAUCE'),
										   ('Sour Cream', 'SAUCE');